### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by shenmo7192** [OldCodeRepo/redict-dtk#20]
n file included from ../eventmonitor.cpp:20:0:
../eventmonitor.h:31:35: fatal error: X11/extensions/record.h: 没有那个文件或目录
 #include <X11/extensions/record.h>
                                   ^
compilation terminated.
Makefile:566: recipe for target 'eventmonitor.o' failed
make: *** [eventmonitor.o] Error 1

**Comment by SuperEndermanSM** [comment]
没有人么？？？

**Comment by rekols** [comment]
eIW0Dnk69454e6nSwuspv9DmS201tQ0D

**Comment by keepgoing365** [comment]
安装以下包即可解决此报错:
sudo apt install libxtst-dev
